const SET_LIGUE_SELECT = "SET_LIGUE_SELECT";
const SET_STATS = "SET_STATS";
const SET_STARS = "SET_STARS";
const CHANGE_CHECKED = "CHANGE_CHECKED";
const SET_FILTER = "SET_FILTER";

export { SET_LIGUE_SELECT, SET_STATS, SET_STARS, CHANGE_CHECKED, SET_FILTER };
