const ADD_NEW_TRANSACTION = "ADD_NEW_TRANSACTION";
const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
const SET_EXCHANGE = "SET_EXCHANGE";

export { ADD_NEW_TRANSACTION, REMOVE_TRANSACTION, SET_EXCHANGE };
